# Generated by Django 2.1.5 on 2019-02-11 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('remainder', models.DateTimeField(blank=True, default=None, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, default=None, max_length=50, null=True)),
            ],
        ),
    ]
