# Generated by Django 2.1.5 on 2019-02-11 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_createnotes'),
    ]

    operations = [
        migrations.AddField(
            model_name='createnotes',
            name='collaborate',
            field=models.ManyToManyField(blank=True, null=True, related_name='collaborated_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='createnotes',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='createnotes',
            name='is_pinned',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='createnotes',
            name='label',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='createnotes',
            name='trash',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='createnotes',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='createnotes',
            name='title',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
