# Generated by Django 2.1.5 on 2019-03-15 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_maplabel'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=None, null=True, upload_to=''),
        ),
    ]
