# Generated by Django 2.1.5 on 2019-03-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createnotes',
            name='is_pinned',
            field=models.NullBooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='createnotes',
            name='label',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
